defaults:
  queue-mode: parallel
jobs:
- name: ebba-cleanup
  active: true
  path: ~/dev/ebba
  run-mode: scheduled
  pre-build: test -f target/release/ebba && mv -f target/release/ebba .
  build: ~/.cargo/bin/cargo clean
  post-build:
    - mkdir -p target/release/
    - test -f ebba && cp -f ebba target/release/ || true
  at: "05:00"
- name: ebba
  active: true
  path: ~/dev/ebba
  build: 
    - ~/.cargo/bin/cargo build --release
    - ~/.cargo/bin/cargo install --path .
  post-build:
    - which gb && gb -I ebba.yaml -a -w
  interval: 3600
