defaults:
  queue-mode: parallel
jobs:
- name: ebba-cleanup
  active: true
  path: ~/dev/ebba
  run-mode: scheduled
  build: ~/.cargo/bin/cargo clean
  at: "05:00"
- name: ebba
  active: true
  path: ~/dev/ebba
  build: 
    - ~/.cargo/bin/cargo build --release
    - ~/.cargo/bin/cargo install --path .
  post-build:
    - which gb && gb -I ebba.yaml -a -w
  interval: 3600
